name: Publish 

on:
  push:
    tags: [ "*" ]
  workflow_dispatch:

# https://github.com/pypa/gh-action-pypi-publish
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/excel2xx
    permissions:
      id-token: write
    steps:
    - name: Build package
      run: pipx run build --sdist --wheel

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
